[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    Basic-Auth = "guest nouensaga"
    Status = "401"

# ✅ リダイレクト設定: i18n の defaultLocale にリダイレクト
[[redirects]]
  from = "/"
  to = "/ja"
  status = 302
